### ISSUE TITLE
Worldgen Error

### ISSUE THREAD

**Issue by cannon9009** [DominicKarma/InfernumModePublic#11]
[22:47:20.937] [WorldGen/ERROR] [tML]: A problem was encountered during world generation
Abyss
System.ArgumentOutOfRangeException: minValue must be less than maxValue (Parameter 'minValue')
   at Terraria.Utilities.UnifiedRandom.Next(Int32 minValue, Int32 maxValue) in tModLoader\Terraria\Utilities\UnifiedRandom.cs:line 103
   at InfernumMode.Content.WorldGeneration.CustomAbyss.GeneratePostSkeletronTiles(Rectangle layer1Area) in InfernumMode\Content\WorldGeneration\CustomAbyss.cs:line 440
   at InfernumMode.Content.WorldGeneration.CustomAbyss.GenerateLayer1() in InfernumMode\Content\WorldGeneration\CustomAbyss.cs:line 236
   at InfernumMode.Content.WorldGeneration.CustomAbyss.Generate() in InfernumMode\Content\WorldGeneration\CustomAbyss.cs:line 122
   at InfernumMode.Core.ILEditingStuff.ReplaceAbyssWorldgen.ChangeAbyssGen(Action orig) in InfernumMode\Core\ILEditingStuff\VanillaCorrectionHooks.cs:line 768
   at Hook<System.Void InfernumMode.Core.ILEditingStuff.ReplaceAbyssWorldgen::ChangeAbyssGen(System.Action)>()
   at SyncProxy<System.Void CalamityMod.World.Abyss:PlaceAbyss()>()
   at CalamityMod.Systems.WorldgenManagementSystem.<>c.<ModifyWorldGenTasks>b__1_27(GenerationProgress progress, GameConfiguration config) in CalamityMod\Systems\WorldgenManagementSystem.cs:line 274
   at DMD<System.Void Terraria.WorldBuilding.WorldGenerator:GenerateWorld(Terraria.WorldBuilding.GenerationProgress)>(WorldGenerator this, GenerationProgress progress)

**Comment by toasty599** [comment]
Does this consistently occur? Or was it a one-off issue.
