### ISSUE TITLE
Outdated build

### ISSUE THREAD

**Issue by LagradOst** [DominicKarma/InfernumModePublic#133]
Unable to load "Calamity Mod Infernum" due to (what I think is an) outdated build. As calamity updated and infernum stopped working.

```[18:28:47.955] [.NET ThreadPool Worker/INFO] [tML]: Adding Content: InfernumMode (Calamity Mod Infernum Mode) v1.9.30
[18:28:48.365] [.NET ThreadPool Worker/WARN] [tML]: Silently Caught Exception: 
System.MissingMethodException: Method not found: 'Void CalamityMod.NPCStats.SetNPCDebuffImmunities(Terraria.NPC)'.
   at MonoMod.Core.Interop.CoreCLR.V60.InvokeCompileMethod(IntPtr functionPtr, IntPtr thisPtr, IntPtr corJitInfo, CORINFO_METHOD_INFO* methodInfo, UInt32 flags, Byte** nativeEntry, UInt32* nativeSizeOfCode) in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Core\Interop\CoreCLR.V60.cs:line 50
   at MonoMod.Core.Platforms.Runtimes.Core21Runtime.JitHookDelegateHolder.CompileMethodHook(IntPtr jit, IntPtr corJitInfo, CORINFO_METHOD_INFO* methodInfo, UInt32 flags, Byte** pNativeEntry, UInt32* pNativeSizeOfCode) in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Core\Platforms\Runtimes\Core21Runtime.cs:line 184
   at System.Runtime.CompilerServices.RuntimeHelpers.PrepareMethod(RuntimeMethodHandleInternal method, IntPtr* pInstantiation, Int32 cInstantiation)
   at System.Runtime.CompilerServices.RuntimeHelpers.PrepareMethod(RuntimeMethodHandleInternal method, IntPtr* pInstantiation, Int32 cInstantiation)
   at System.Runtime.CompilerServices.RuntimeHelpers.PrepareMethod(RuntimeMethodHandle method, RuntimeTypeHandle[] instantiation)
   at Terraria.ModLoader.Core.AssemblyManager.ForceJITOnMethod(MethodBase method) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 405
   at Terraria.ModLoader.Core.AssemblyManager.<>c__DisplayClass23_0.<JITAssemblies>b__1(MethodBase method) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 378
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

[18:28:48.661] [.NET ThreadPool Worker/WARN] [tML]: Silently Caught Exception: 
Terraria.ModLoader.Exceptions.JITException: 
In InfernumMode.Content.BehaviorOverrides.BossAIs.DoG.DoGPhase1BodyBehaviorOverride.KillUnbalancedDebuffs, Method not found: 'Void CalamityMod.NPCStats.SetNPCDebuffImmunities(Terraria.NPC)'.

   at Terraria.ModLoader.Core.AssemblyManager.JITAssemblies(IEnumerable`1 assemblies, PreJITFilter filter) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 398
   at Terraria.ModLoader.Core.AssemblyManager.JITMod(Mod mod) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 355
   at Terraria.ModLoader.ModContent.<>c.<Load>b__43_0(Mod mod) in tModLoader\Terraria\ModLoader\ModContent.cs:line 283
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction) in tModLoader\Terraria\ModLoader\ModContent.cs:line 377
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 282
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 126
   at Terraria.ModLoader.ModLoader.<>c__DisplayClass46_0.<BeginLoad>b__0() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 106
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

[18:28:48.900] [.NET ThreadPool Worker/ERROR] [tML]: An error occurred while loading InfernumMode v1.9.30
It has been detected that this mod was built for tModLoader v2023.6.25.32
However, you are using tModLoader v2023.8.3.0
The mod will need to be updated to match the current tModLoader version, or may be incompatible with the version of some of your other mods. Click the 'Open Web Help' button to learn more.
The mod(s) have been automatically disabled.
Terraria.ModLoader.Exceptions.JITException: 
In InfernumMode.Content.BehaviorOverrides.BossAIs.DoG.DoGPhase1BodyBehaviorOverride.KillUnbalancedDebuffs, Method not found: 'Void CalamityMod.NPCStats.SetNPCDebuffImmunities(Terraria.NPC)'.

   at Terraria.ModLoader.Core.AssemblyManager.JITAssemblies(IEnumerable`1 assemblies, PreJITFilter filter) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 398
   at Terraria.ModLoader.Core.AssemblyManager.JITMod(Mod mod) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 355
   at Terraria.ModLoader.ModContent.<>c.<Load>b__43_0(Mod mod) in tModLoader\Terraria\ModLoader\ModContent.cs:line 283
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction) in tModLoader\Terraria\ModLoader\ModContent.cs:line 377
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 282
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 126
[18:28:48.901] [.NET ThreadPool Worker/INFO] [tML]: Disabling Mod: InfernumMode
```
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12777653/client.log)

**Comment by LagradOst** [comment]
fixed as of https://github.com/DominicKarma/InfernumModePublic/commit/4308327ede636abba482a5537b2718bea909c249
