### ISSUE TITLE
Error when trying to load world

### ISSUE THREAD

**Issue by cybersymptomz** [DominicKarma/InfernumModePublic#9]
Good evening. I would like to report an error I'm encountering when trying to load my world with Infernum mod enabled. For context, this error started happening between play sessions, for no apparent reason. At one time I was playing, exited the word normally by cliking "Save and exit", and when I tried to open the world later, the error started appearing. 
Disabling Infernum mod lets me load the world normally. Reenabling it makes the error appear again. Here is the error log:

```
[20:05:23.009] [.NET ThreadPool Worker/WARN] [tML]: Silently Caught Exception: 
System.ArgumentException: Destination is too short. (Parameter 'destination')
   at InfernumMode.Core.TileData.SakuraTreeSystem.LoadWorldData(TagCompound tag) in InfernumMode\Core\TileData\SakuraTreeSystem.cs:line 163
   at Terraria.ModLoader.IO.WorldIO.LoadModData(IList`1 list) in tModLoader\Terraria\ModLoader\IO\WorldIO.cs:line 512
   at Terraria.ModLoader.Default.UnloadedSystem.LoadWorldData(TagCompound tag) in tModLoader\Terraria\ModLoader\Default\UnloadedSystem.cs:line 45
   at Terraria.ModLoader.IO.WorldIO.LoadModData(IList`1 list) in tModLoader\Terraria\ModLoader\IO\WorldIO.cs:line 512
   at Terraria.ModLoader.IO.WorldIO.Load(String path, Boolean isCloudSave) in tModLoader\Terraria\ModLoader\IO\WorldIO.cs:line 83
   at Terraria.IO.WorldFile.LoadWorld(Boolean loadFromCloud) in tModLoader\Terraria\IO\WorldFile.cs:line 503
   at Terraria.WorldGen.playWorldCallBack(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 2688
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

[20:05:23.011] [.NET ThreadPool Worker/WARN] [tML]: Silently Caught Exception: 
Terraria.ModLoader.Exceptions.CustomModDataException: Error in reading custom world data for InfernumMode
   at Terraria.ModLoader.IO.WorldIO.LoadModData(IList`1 list) in tModLoader\Terraria\ModLoader\IO\WorldIO.cs:line 512
   at Terraria.ModLoader.Default.UnloadedSystem.LoadWorldData(TagCompound tag) in tModLoader\Terraria\ModLoader\Default\UnloadedSystem.cs:line 45
   at Terraria.ModLoader.IO.WorldIO.LoadModData(IList`1 list) in tModLoader\Terraria\ModLoader\IO\WorldIO.cs:line 512
   at Terraria.ModLoader.IO.WorldIO.Load(String path, Boolean isCloudSave) in tModLoader\Terraria\ModLoader\IO\WorldIO.cs:line 83
   at Terraria.IO.WorldFile.LoadWorld(Boolean loadFromCloud) in tModLoader\Terraria\IO\WorldFile.cs:line 503
   at Terraria.WorldGen.playWorldCallBack(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 2688
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

[20:05:23.011] [.NET ThreadPool Worker/WARN] [tML]: Silently Caught Exception: 
Terraria.ModLoader.Exceptions.CustomModDataException: Error in reading custom world data for ModLoader
   at Terraria.ModLoader.IO.WorldIO.LoadModData(IList`1 list) in tModLoader\Terraria\ModLoader\IO\WorldIO.cs:line 512
   at Terraria.ModLoader.IO.WorldIO.Load(String path, Boolean isCloudSave) in tModLoader\Terraria\ModLoader\IO\WorldIO.cs:line 83
   at Terraria.IO.WorldFile.LoadWorld(Boolean loadFromCloud) in tModLoader\Terraria\IO\WorldFile.cs:line 503
   at Terraria.WorldGen.playWorldCallBack(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 2688
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

The log seems to indicate that the error happens due to that sakura tree-related item. I remember having found the sakura bud when cutting some trees, but didn't get to do anything with it, just stored the item in my magic storage.

**Comment by toasty599** [comment]
Should hopefully be fixed in the next patch :)

**Comment by cybersymptomz** [comment]
Do you think its going to take much longer to release the patch? I would like to know if I should abandon my Infernum world right know and continue my playthrough in another one.

**Comment by toasty599** [comment]
ETA is currently a few days, if things continue to go as they are.

**Comment by cybersymptomz** [comment]
Can confirm that it was fixed.

**Comment by cybersymptomz** [comment]
Scratch that. After saving and exiting, and then trying to load the world again: now tModLoader straight up crashes, doesn't even leave any errors in the client.log. Disabling Infernum lets me load the world normally again.

**Comment by toasty599** [comment]
Try on the latest version

**Comment by cybersymptomz** [comment]
Yep, seems to be back to normal. Tried to exit and reload several times and didn't encounter the problem again. Will report here if anything happens.
