### ISSUE TITLE
Calamity Infernum mode does not start (gets disabled)

### ISSUE THREAD

**Issue by DerpThePro** [DominicKarma/InfernumModePublic#91]
My game does not like Infernum mode, it disables it every time I try to enable it, here are the logs;

"
The mod(s) have been automatically disabled.
Terraria.ModLoader.Exceptions.GetLoadableTypesException: This mod seems to inherit from classes in another mod. Use the [ExtendsFromMod] attribute to allow this mod to load when that mod is not enabled.
Could not find type 'CalamityMod.Items.Weapons.Rogue.RogueWeapon' in assembly ''.
 ---> System.TypeLoadException: Could not find type 'CalamityMod.Items.Weapons.Rogue.RogueWeapon' in assembly ''.
   at System.Reflection.TypeLoading.Ecma.EcmaResolver.ComputeTypeRefResolution(TypeReferenceHandle handle, EcmaModule module)
   at System.Reflection.TypeLoading.Ecma.EcmaResolver.<>c.<.cctor>b__15_1(EntityHandle h, EcmaModule m)
   at System.Reflection.TypeLoading.Ecma.EcmaResolver.ResolveTypeDefRefOrSpec(EntityHandle handle, EcmaModule module, TypeContext& typeContext)
   at System.Reflection.TypeLoading.Ecma.EcmaDefinitionType.SpecializeBaseType(RoType[] instantiation)
   at System.Reflection.TypeLoading.RoType.ComputeBaseType()
   at System.Reflection.TypeLoading.RoType.GetRoBaseType()
   at Terraria.ModLoader.Core.AssemblyManager.IsLoadable(ModLoadContext mod, Type type) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 330
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Terraria.ModLoader.Core.AssemblyManager.GetLoadableTypes(ModLoadContext mod, MetadataLoadContext mlc) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 314
   --- End of inner exception stack trace ---
   at Terraria.ModLoader.Core.AssemblyManager.GetLoadableTypes(ModLoadContext mod, MetadataLoadContext mlc) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 314
   at Terraria.ModLoader.Core.AssemblyManager.ModLoadContext.LoadAssemblies() in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 66
   at Terraria.ModLoader.Core.AssemblyManager.InstantiateMods(List`1 modsToLoad, CancellationToken token) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 249
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 119
[17:01:29.625] [.NET ThreadPool Worker/INFO] [tML]: Disabling Mod: InfernumMode

"

VERSION: Legacy-1.4.3

Mod list:

AlchemistNPC LITE
Betterblending
Betterzoom
BossChecklist
Bowmod
BTitles
Calamity
Calamity music
Cobler mod
colored damage types
combinations
Compare item stats
Dialogue tweak
DPS extreme
Fargo Soul mod, DLC, music, & mutant
Hero's mod
High trees
HPAware
Improve game
Infernum mode (issue)
item checklist
lights
Lookmod
Magic storage
Melee effects
Luiafk
Particle library
Pittaubuildingmod
Pointshop
Recipe browser
Shopquotes mod
structure helper
Subworld Library
SummonsUI
Terrarchitect
TerrariaAmbience
TerrariaAmbience API
Vitality
Weapondisplay
wingtimeUI
wombatQOL
Worldgenpreviewer
Bosschecklist
BossesasNPCs
Ore excavator
Wingslot extra

(I think thats all of them)

**Comment by toasty599** [comment]
Update your calamity mod.
