### ISSUE TITLE
Error in World Updating Logic

### ISSUE THREAD

**Issue by absoluteAquarian** [DominicKarma/InfernumModePublic#92]
I've been getting many reports of Magic Storage suddenly not working in multiplayer, and after receiving a `server.log` file from a user, this mod appears to be the source of the problem.

The following error stacktrace was reported in the aforementioned log file:
```
[21:13:32.390] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at InfernumMode.Core.GlobalInstances.Systems.NuclearTerrorSpawnSystem.PreUpdateWorld() in InfernumMode\Core\GlobalInstances\Systems\NuclearTerrorSpawnSystem.cs:line 46
   at Terraria.ModLoader.SystemLoader.PreUpdateWorld() in tModLoader\Terraria\ModLoader\SystemLoader.cs:line 299
   at DMD<Terraria.WorldGen::UpdateWorld>()
   at DMD<Terraria.Main::DoUpdateInWorld>(Main this, Stopwatch sw)
   at Terraria.Main.DoUpdate(GameTime& gameTime) in tModLoader\Terraria\Main.cs:line 13223
   at Terraria.Main.Update(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 12778
   at DMD<Terraria.Main::DedServ_PostModLoad>(Main this, Boolean& reloadMods)
   at Terraria.Main.DedServ() in tModLoader\Terraria\Main.cs:line 4215
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 229
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 188
   at MonoLaunch.<>c__DisplayClass1_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 56
   at System.Threading.Thread.StartCallback()
```

This point in the world updating logic is before tile entities are updated, which causes the Storage Heart to never process client requests, making depositing items into and withdrawing items from storage do nothing.

**Comment by toasty599** [comment]
Fixed for next patch.
