### ISSUE TITLE
Infernum unable to load itself

### ISSUE THREAD

**Issue by chaapz** [DominicKarma/InfernumModePublic#93]
An error occurred while loading InfernumMode v1.9.29
The mod will need to be updated to match the current tModLoader version, or may be incompatible with the version of some of your other mods. Click the 'Open Web Help' button to learn more.
The mod(s) have been automatically disabled.
Terraria.ModLoader.Exceptions.JITException: 
In InfernumMode.Content.UI.InfernumDifficulty..ctor, Field not found: 'CalamityMod.Systems.DifficultyModeSystem.Difficulties'.

   at Terraria.ModLoader.Core.AssemblyManager.JITAssemblies(IEnumerable`1 assemblies, PreJITFilter filter) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 398
   at Terraria.ModLoader.ModContent.<>c.<Load>b__42_0(Mod mod) in tModLoader\Terraria\ModLoader\ModContent.cs:line 287
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction) in tModLoader\Terraria\ModLoader\ModContent.cs:line 368
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 277
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 125

It was working fine until just recently. Did the calamity update break it?
It's up to date, so it's not the wrong version.

**Comment by gregrebholz** [comment]
Same here.  Calamity moved to 2.0.3.3 about 1 hour ago and Infernum stopped loading with the above error.

**Comment by ZapGamer** [comment]
yeah same error here.

**Comment by Narwhalian** [comment]
yep

**Comment by quandale-dingolius** [comment]
same

**Comment by JeacyG** [comment]
same

**Comment by toasty599** [comment]
Calamity decided to update an hour after I went to bed, without letting me know ahead of time. It will be fixed shortly

**Comment by chaapz** [comment]
> Calamity decided to update an hour after I went to bed, without letting me know ahead of time. It will be fixed shortly

thanks so much for being so on top of it! I was expecting to have to wait at least a week or two
